package entity.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Surveys was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Surveys extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> ALLOW_REPORTS = new Property<String>("allowReports");
    public static final Property<String> ANONYMOUS = new Property<String>("anonymous");
    public static final Property<Integer> CATI_PANEL_ID = new Property<Integer>("catiPanelId");
    public static final Property<Integer> CLIENT_ID = new Property<Integer>("clientId");
    public static final Property<String> CLOSED = new Property<String>("closed");
    public static final Property<Integer> CONFIDENTIAL = new Property<Integer>("confidential");
    public static final Property<String> DELAYED = new Property<String>("delayed");
    public static final Property<Integer> DELETED = new Property<Integer>("deleted");
    public static final Property<Date> END_DATE = new Property<Date>("endDate");
    public static final Property<Integer> FOLDER_ID = new Property<Integer>("folderId");
    public static final Property<String> IMPLEMENTATION = new Property<String>("implementation");
    public static final Property<String> JOB_TYPE = new Property<String>("jobType");
    public static final Property<String> NOTES = new Property<String>("notes");
    public static final Property<String> PUBLISHED_ACTIVE = new Property<String>("publishedActive");
    public static final Property<Date> PUBLISHED_END_DATE = new Property<Date>("publishedEndDate");
    public static final Property<String> PUBLISHED_PASSWORD = new Property<String>("publishedPassword");
    public static final Property<Date> PUBLISHED_START_DATE = new Property<Date>("publishedStartDate");
    public static final Property<Integer> QUESTIONNAIRE_ID = new Property<Integer>("questionnaireId");
    public static final Property<Integer> RECIPIENT_COUNT = new Property<Integer>("recipientCount");
    public static final Property<String> REMINDER = new Property<String>("reminder");
    public static final Property<Date> REMINDER_DATE = new Property<Date>("reminderDate");
    public static final Property<String> RUN_STATUS = new Property<String>("runStatus");
    public static final Property<String> S_LANGUAGE = new Property<String>("sLanguage");
    public static final Property<String> S_TYPE = new Property<String>("sType");
    public static final Property<String> SSL_ENABLED = new Property<String>("sslEnabled");
    public static final Property<Date> START_DATE = new Property<Date>("startDate");
    public static final Property<String> STATUS = new Property<String>("status");
    public static final Property<Integer> TARGET_RESP = new Property<Integer>("targetResp");
    public static final Property<String> TEMPLATE_TYPE = new Property<String>("templateType");
    public static final Property<String> TITLE = new Property<String>("title");

    public void setAllowReports(String allowReports) {
        writeProperty("allowReports", allowReports);
    }
    public String getAllowReports() {
        return (String)readProperty("allowReports");
    }

    public void setAnonymous(String anonymous) {
        writeProperty("anonymous", anonymous);
    }
    public String getAnonymous() {
        return (String)readProperty("anonymous");
    }

    public void setCatiPanelId(Integer catiPanelId) {
        writeProperty("catiPanelId", catiPanelId);
    }
    public Integer getCatiPanelId() {
        return (Integer)readProperty("catiPanelId");
    }

    public void setClientId(Integer clientId) {
        writeProperty("clientId", clientId);
    }
    public Integer getClientId() {
        return (Integer)readProperty("clientId");
    }

    public void setClosed(String closed) {
        writeProperty("closed", closed);
    }
    public String getClosed() {
        return (String)readProperty("closed");
    }

    public void setConfidential(Integer confidential) {
        writeProperty("confidential", confidential);
    }
    public Integer getConfidential() {
        return (Integer)readProperty("confidential");
    }

    public void setDelayed(String delayed) {
        writeProperty("delayed", delayed);
    }
    public String getDelayed() {
        return (String)readProperty("delayed");
    }

    public void setDeleted(Integer deleted) {
        writeProperty("deleted", deleted);
    }
    public Integer getDeleted() {
        return (Integer)readProperty("deleted");
    }

    public void setEndDate(Date endDate) {
        writeProperty("endDate", endDate);
    }
    public Date getEndDate() {
        return (Date)readProperty("endDate");
    }

    public void setFolderId(Integer folderId) {
        writeProperty("folderId", folderId);
    }
    public Integer getFolderId() {
        return (Integer)readProperty("folderId");
    }

    public void setImplementation(String implementation) {
        writeProperty("implementation", implementation);
    }
    public String getImplementation() {
        return (String)readProperty("implementation");
    }

    public void setJobType(String jobType) {
        writeProperty("jobType", jobType);
    }
    public String getJobType() {
        return (String)readProperty("jobType");
    }

    public void setNotes(String notes) {
        writeProperty("notes", notes);
    }
    public String getNotes() {
        return (String)readProperty("notes");
    }

    public void setPublishedActive(String publishedActive) {
        writeProperty("publishedActive", publishedActive);
    }
    public String getPublishedActive() {
        return (String)readProperty("publishedActive");
    }

    public void setPublishedEndDate(Date publishedEndDate) {
        writeProperty("publishedEndDate", publishedEndDate);
    }
    public Date getPublishedEndDate() {
        return (Date)readProperty("publishedEndDate");
    }

    public void setPublishedPassword(String publishedPassword) {
        writeProperty("publishedPassword", publishedPassword);
    }
    public String getPublishedPassword() {
        return (String)readProperty("publishedPassword");
    }

    public void setPublishedStartDate(Date publishedStartDate) {
        writeProperty("publishedStartDate", publishedStartDate);
    }
    public Date getPublishedStartDate() {
        return (Date)readProperty("publishedStartDate");
    }

    public void setQuestionnaireId(Integer questionnaireId) {
        writeProperty("questionnaireId", questionnaireId);
    }
    public Integer getQuestionnaireId() {
        return (Integer)readProperty("questionnaireId");
    }

    public void setRecipientCount(Integer recipientCount) {
        writeProperty("recipientCount", recipientCount);
    }
    public Integer getRecipientCount() {
        return (Integer)readProperty("recipientCount");
    }

    public void setReminder(String reminder) {
        writeProperty("reminder", reminder);
    }
    public String getReminder() {
        return (String)readProperty("reminder");
    }

    public void setReminderDate(Date reminderDate) {
        writeProperty("reminderDate", reminderDate);
    }
    public Date getReminderDate() {
        return (Date)readProperty("reminderDate");
    }

    public void setRunStatus(String runStatus) {
        writeProperty("runStatus", runStatus);
    }
    public String getRunStatus() {
        return (String)readProperty("runStatus");
    }

    public void setSLanguage(String sLanguage) {
        writeProperty("sLanguage", sLanguage);
    }
    public String getSLanguage() {
        return (String)readProperty("sLanguage");
    }

    public void setSType(String sType) {
        writeProperty("sType", sType);
    }
    public String getSType() {
        return (String)readProperty("sType");
    }

    public void setSslEnabled(String sslEnabled) {
        writeProperty("sslEnabled", sslEnabled);
    }
    public String getSslEnabled() {
        return (String)readProperty("sslEnabled");
    }

    public void setStartDate(Date startDate) {
        writeProperty("startDate", startDate);
    }
    public Date getStartDate() {
        return (Date)readProperty("startDate");
    }

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }

    public void setTargetResp(Integer targetResp) {
        writeProperty("targetResp", targetResp);
    }
    public Integer getTargetResp() {
        return (Integer)readProperty("targetResp");
    }

    public void setTemplateType(String templateType) {
        writeProperty("templateType", templateType);
    }
    public String getTemplateType() {
        return (String)readProperty("templateType");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

}
